import PlaceholderImage from 'asset/image/placeholder.jpg';
import MiamiImage from 'asset/image/miami.jpg';
import NewYorkImage from 'asset/image/new-york.jpg';
import MontrealImage from 'asset/image/montreal.jpg';
import VancouverImage from 'asset/image/vancouver.jpg';
import TorontoImage from 'asset/image/toronto.jpg';

const homeMockDataAlt = {
  sections: {
    placeCtas: {
      title: 'Find your getaway',
      description:
        'Our spaces are designed for comfort - whether you are working, relaxing, or craving some spaces',
      places: [
        {
          id: 2,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 9,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 16,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 23,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 30,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 37,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 44,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 51,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 58,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 65,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 72,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 79,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 86,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 93,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 100,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 107,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 114,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 121,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 128,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 135,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 142,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 149,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 156,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 163,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 170,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 177,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 184,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 191,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 198,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 205,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 212,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 219,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 226,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 233,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 240,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 247,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 254,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 261,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 268,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 275,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 282,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 289,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 296,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 303,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 310,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 317,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 324,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 331,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 338,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 345,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 352,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 359,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 366,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 373,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 380,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 387,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 394,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 401,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 408,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 415,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 422,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 429,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 436,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 443,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 450,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 457,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 464,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 471,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 478,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 485,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 492,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 499,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 506,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 513,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 520,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 527,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 534,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 541,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 548,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 555,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 562,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 569,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 576,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 583,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 590,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 597,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 604,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 611,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 618,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 625,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 632,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 639,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 646,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 653,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 660,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 667,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 674,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 681,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 688,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 695,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 702,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 709,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 716,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 723,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 730,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 737,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 744,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 751,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 758,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 765,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 772,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 779,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 786,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 793,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 800,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 807,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 814,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 821,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 828,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 835,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 842,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 849,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 856,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 863,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 870,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 877,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 884,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 891,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 898,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 905,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 912,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 919,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 926,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 933,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 940,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 947,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 954,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 961,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 968,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 975,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 982,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 989,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 996,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1003,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1010,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1017,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1024,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1031,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1038,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1045,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1052,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1059,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1066,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1073,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1080,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1087,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1094,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1101,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1108,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1115,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1122,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1129,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1136,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1143,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1150,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1157,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1164,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1171,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1178,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1185,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1192,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1199,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1206,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1213,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1220,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1227,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1234,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1241,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1248,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1255,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1262,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1269,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1276,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1283,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1290,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1297,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1304,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1311,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1318,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1325,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1332,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1339,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1346,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1353,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1360,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1367,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1374,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1381,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1388,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1395,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1402,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1409,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1416,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1423,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1430,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1437,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1444,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1451,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1458,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1465,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1472,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1479,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1486,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1493,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1500,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1507,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1514,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1521,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1528,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1535,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1542,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1549,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1556,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1563,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1570,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1577,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1584,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1591,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1598,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1605,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1612,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1619,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1626,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1633,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1640,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1647,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1654,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1661,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1668,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1675,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1682,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1689,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1696,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1703,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1710,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1717,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1724,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1731,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1738,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1745,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1752,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1759,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1766,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1773,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1780,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1787,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1794,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1801,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1808,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1815,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
        {
          id: 1822,
          image: PlaceholderImage,
          imageLabel: 'From $126',
          title: '408 St. Jacques | 1 Br',
          location: 'Old Montreal, Montreal',
        },
      ],
    },
    cityCtas: {
      title: '20+ cities to explore',
      places: [
        {
          id: 1,
          image: MiamiImage,
          title: 'Miami',
        },
        {
          id: 2,
          image: NewYorkImage,
          title: 'New York',
          imageLabel: 'New',
        },
        {
          id: 3,
          image: MontrealImage,
          title: 'Montreal',
        },
        {
          id: 4,
          image: VancouverImage,
          title: 'Vancouver',
        },
        {
          id: 1,
          image: TorontoImage,
          title: 'Toronto',
        },
      ],
    },
  },
};

export default homeMockDataAlt;
